#!/bin/bash

# Fix Git Bash on Windows → avoid path rewriting
export MSYS_NO_PATHCONV=1
export MSYS2_ARG_CONV_EXCL="*"


echo "📦 Installation du projet..."

# Build des images Docker
docker compose build

# Démarrage du container PHP
docker compose up -d php

# Créer les dossiers et fichiers nécessaires
docker compose exec php mkdir /var/www/html/data
docker compose exec php touch /var/www/html/data/database.sqlite

# Installer composer dans le container si pas présent
docker compose exec php bash -c "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\" && php composer-setup.php --install-dir=/usr/local/bin --filename=composer && php -r \"unlink('composer-setup.php');\" || echo 'Composer déjà installé'"

# Installer les dépendances via Composer
docker compose exec php composer install

# Initialiser la BDD SQLite
docker compose exec php php sqlite/initialize.php

docker compose down

echo "✅ Installation terminée !"
